spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/girl?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    #设为true，可以在控制台可以看到sql语句
    show-sql: true

